### ISSUE TITLE
fix: book status quero_ler

### ISSUE THREAD

**Issue by gabrielamarqs** [shelfiie/Shelfie-front-end#152]
- se está como quero_ler OU mudar para lendo OU não mostrar o ler
![image](https://github.com/user-attachments/assets/76e15382-6bd8-416d-ac9c-112a5a3f56ab)

**Comment by mayspiek** [comment]
@gabrielamarqs desabilitei o botão caso esteja no status quero ler
a lógica até funcionou mas como a primeira req retorna erro 403, o retorno geral já caia no erro e não retornava feedback positivo pro usuário.
